# Generated by Django 5.0 on 2023-12-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
