# Generated by Django 5.0 on 2023-12-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_brands_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltypes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
